install:
    - sudo add-apt-repository ppa:pi-rho/dev -y
    - sudo apt-get update -q
    - sudo apt-get install vim-gtk

before_script:
    - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
    - git clone https://github.com/thinca/vim-themis --branch v1.4 --single-branch --depth 1 /tmp/vim-themis
    - vim --version

script:
    - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser plugin autoload
    - /tmp/vim-themis/bin/themis
    - /tmp/vim-themis/bin/themis --target vanish1
    - cat /tmp/hoge
    - cat /tmp/hoge0
    - cat /tmp/hoge1
    - cat /tmp/hogeorg


